# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  refresh-token:
    cmds:
      - doppler run -- ./dev-refresh-token.sh

  list-surfaces:
    cmds:
      - ./dev-curl.sh https://fc103km01j.execute-api.ap-southeast-2.amazonaws.com/v1/surface
