# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  auth-refresh:
    cmds:
      - doppler run ./refresh.sh

  list-surfaces:
    vars:
      ART_CLI_BASE:
        sh: doppler secrets get ART_CLI_BASE --plain
    cmds:
      - doppler run ./curl.sh {{.ART_CLI_BASE}}/surface

  # task patch-surface SURFACE_ID=... BODY='{"Name":"Test 1","Rotation":270}'
  patch-surface:
    vars:
      ART_CLI_BASE:
        sh: doppler secrets get ART_CLI_BASE --plain
    cmds:
      - 'doppler run -- ./curl.sh -X PATCH -H "content-type: application/json" -d{{.BODY | shellQuote}} {{.ART_CLI_BASE}}/surface/{{.SURFACE_ID}}'

  hello-surface:
    vars:
      ART_CLI_BASE:
        sh: doppler secrets get ART_CLI_BASE --plain
    cmds:
      - "doppler run -- ./curl.sh {{.ART_CLI_BASE}}/surface/{{.SURFACE_ID}}/hello"

  upload-asset:
    cmds:
      - ./upload-asset.sh "{{.FILENAME}}"

  list-assets:
    vars:
      ART_CLI_BASE:
        sh: doppler secrets get ART_CLI_BASE --plain
    cmds:
      - doppler run ./curl.sh {{.ART_CLI_BASE}}/asset

  # task patch-asset ASSET_ID=MWx_4VJJEvr0OUoL6vCXV BODY='{"Name":"The Red Caboose Motel","Artist":"Cate Hughes","Source":"https://www.etsy.com/au/shop/LuckyHues","Notes":"Downie Live - Travels by Train"}'
  patch-asset:
    vars:
      ART_CLI_BASE:
        sh: doppler secrets get ART_CLI_BASE --plain
    cmds:
      - 'doppler run -- ./curl.sh -X PATCH -H "content-type: application/json" -d{{.BODY | shellQuote}} {{.ART_CLI_BASE}}/asset/{{.ASSET_ID}}'

  get-asset:
    vars:
      ART_CLI_BASE:
        sh: doppler secrets get ART_CLI_BASE --plain
    cmds:
      - doppler run ./curl.sh {{.ART_CLI_BASE}}/asset/{{.ASSET_ID}}

  create-playlist:
    vars:
      ART_CLI_BASE:
        sh: doppler secrets get ART_CLI_BASE --plain
    cmds:
      - 'doppler run -- ./curl.sh -X POST -H "content-type: application/json" -d{{.BODY | shellQuote}} {{.ART_CLI_BASE}}/playlist'

  list-playlists:
    vars:
      ART_CLI_BASE:
        sh: doppler secrets get ART_CLI_BASE --plain
    cmds:
      - 'doppler run -- ./curl.sh -X GET -H "content-type: application/json" {{.ART_CLI_BASE}}/playlist'

  get-playlist:
    vars:
      ART_CLI_BASE:
        sh: doppler secrets get ART_CLI_BASE --plain
    cmds:
      - doppler run -- ./curl.sh -v {{.ART_CLI_BASE}}/playlist/{{.PLAYLIST_ID | shellQuote}}

  get-playlist-version:
    vars:
      ART_CLI_BASE:
        sh: doppler secrets get ART_CLI_BASE --plain
    cmds:
      - 'doppler run -- ./curl.sh -H ''If-Match: "{{.ETAG | shellQuote}}"'' -v {{.ART_CLI_BASE}}/playlist/{{.PLAYLIST_ID | shellQuote}}'

  # task patch-playlist PLAYLIST_ID=... ETAG=... BODY='{"Name":"Test 2"}'
  # task patch-playlist PLAYLIST_ID=... ETAG=... BODY='{"SceneChanges":[{"Change":"Add","Duration":3600,"Assets":[{"AssetId":"add-to-start"}],"Before":0}]}'
  # task patch-playlist PLAYLIST_ID=... ETAG=... BODY='{"SceneChanges":[{"Change":"Add","Duration":3600,"Assets":[{"AssetId":"add-to-the-middle"}],"Before":5}]}'
  # task patch-playlist PLAYLIST_ID=... ETAG=... BODY='{"SceneChanges":[{"Change":"Add","Duration":3600,"Assets":[{"AssetId":"add-to-end"}]}]}'
  # task patch-playlist PLAYLIST_ID=... ETAG=... BODY='{"SceneChanges":[{"Change":"Remove","Scene":0}]}'
  patch-playlist:
    vars:
      ART_CLI_BASE:
        sh: doppler secrets get ART_CLI_BASE --plain
    cmds:
      - 'doppler run -- ./curl.sh -H ''If-Match: "{{.ETAG | shellQuote}}"'' -H "content-type: application/json" -X PATCH -d{{.BODY | shellQuote}} -v {{.ART_CLI_BASE}}/playlist/{{.PLAYLIST_ID | shellQuote}}'
