name: PR
on: pull_request
jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    name: Pulumi Preview
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.PULUMI_READONLY_ROLE_ARN }}
        role-session-name: art-preview
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: npm install
    - uses: pulumi/actions@v3
      with:
        command: preview
        stack-name: dev
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        PULUMI_CI: pr
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}